# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "express_translate"
  s.version = "1.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karl"]
  s.date = "2014-07-02"
  s.description = "longer description of your gem"
  s.email = "karl@rubify.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    ".watchr",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/.DS_Store",
    "app/assets/.DS_Store",
    "app/assets/images/.DS_Store",
    "app/assets/images/express_translate/.DS_Store",
    "app/assets/images/express_translate/add.png",
    "app/assets/images/express_translate/back.png",
    "app/assets/images/express_translate/blur.svg",
    "app/assets/images/express_translate/close.png",
    "app/assets/images/express_translate/embed.png",
    "app/assets/images/express_translate/file.png",
    "app/assets/images/express_translate/flags/Chad.png",
    "app/assets/images/express_translate/flags/ar.png",
    "app/assets/images/express_translate/flags/az.png",
    "app/assets/images/express_translate/flags/bg.png",
    "app/assets/images/express_translate/flags/bs.png",
    "app/assets/images/express_translate/flags/ca.png",
    "app/assets/images/express_translate/flags/cs.png",
    "app/assets/images/express_translate/flags/da.png",
    "app/assets/images/express_translate/flags/de.png",
    "app/assets/images/express_translate/flags/el.png",
    "app/assets/images/express_translate/flags/en-GB.png",
    "app/assets/images/express_translate/flags/en.png",
    "app/assets/images/express_translate/flags/es.png",
    "app/assets/images/express_translate/flags/et.png",
    "app/assets/images/express_translate/flags/fa.png",
    "app/assets/images/express_translate/flags/fi.png",
    "app/assets/images/express_translate/flags/fr.png",
    "app/assets/images/express_translate/flags/he.png",
    "app/assets/images/express_translate/flags/hr.png",
    "app/assets/images/express_translate/flags/hu.png",
    "app/assets/images/express_translate/flags/id.png",
    "app/assets/images/express_translate/flags/is.png",
    "app/assets/images/express_translate/flags/it.png",
    "app/assets/images/express_translate/flags/ja.png",
    "app/assets/images/express_translate/flags/ko.png",
    "app/assets/images/express_translate/flags/lt.png",
    "app/assets/images/express_translate/flags/lv.png",
    "app/assets/images/express_translate/flags/my.png",
    "app/assets/images/express_translate/flags/nb.png",
    "app/assets/images/express_translate/flags/nl.png",
    "app/assets/images/express_translate/flags/no.png",
    "app/assets/images/express_translate/flags/pl.png",
    "app/assets/images/express_translate/flags/pt-BR.png",
    "app/assets/images/express_translate/flags/pt.png",
    "app/assets/images/express_translate/flags/ro.png",
    "app/assets/images/express_translate/flags/ru.png",
    "app/assets/images/express_translate/flags/sk.png",
    "app/assets/images/express_translate/flags/sl.png",
    "app/assets/images/express_translate/flags/sv.png",
    "app/assets/images/express_translate/flags/th.png",
    "app/assets/images/express_translate/flags/tr.png",
    "app/assets/images/express_translate/flags/uk.png",
    "app/assets/images/express_translate/flags/vi.png",
    "app/assets/images/express_translate/flags/zh-CN.png",
    "app/assets/images/express_translate/flags/zh-HK.png",
    "app/assets/images/express_translate/flags/zh-TW.png",
    "app/assets/images/express_translate/jquery_ui/animated-overlay.gif",
    "app/assets/images/express_translate/jquery_ui/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_diagonals-thick_20_666666_40x40.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_flat_10_000000_40x100.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_glass_100_f6f6f6_1x400.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_glass_100_fdf5ce_1x400.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_glass_65_ffffff_1x400.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "app/assets/images/express_translate/jquery_ui/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "app/assets/images/express_translate/jquery_ui/ui-icons_222222_256x240.png",
    "app/assets/images/express_translate/jquery_ui/ui-icons_228ef1_256x240.png",
    "app/assets/images/express_translate/jquery_ui/ui-icons_ef8c08_256x240.png",
    "app/assets/images/express_translate/jquery_ui/ui-icons_ffd27a_256x240.png",
    "app/assets/images/express_translate/jquery_ui/ui-icons_ffffff_256x240.png",
    "app/assets/images/express_translate/key-white.png",
    "app/assets/images/express_translate/login.png",
    "app/assets/images/express_translate/logout.png",
    "app/assets/images/express_translate/password.png",
    "app/assets/images/express_translate/remove.png",
    "app/assets/images/express_translate/setting.png",
    "app/assets/images/express_translate/username.png",
    "app/assets/images/express_translate/wselect/.DS_Store",
    "app/assets/images/express_translate/wselect/arrow-down.png",
    "app/assets/javascript/express_translate/application.js",
    "app/assets/javascript/express_translate/base.js",
    "app/assets/javascript/express_translate/bpopup.js",
    "app/assets/javascript/express_translate/handlebars-v1.3.0.js",
    "app/assets/javascript/express_translate/jquery-ui-1.10.4.js",
    "app/assets/javascript/express_translate/translate.layout.js",
    "app/assets/javascript/express_translate/wSelect.js",
    "app/assets/stylesheets/.DS_Store",
    "app/assets/stylesheets/express_translate/.DS_Store",
    "app/assets/stylesheets/express_translate/animate.css",
    "app/assets/stylesheets/express_translate/application.css",
    "app/assets/stylesheets/express_translate/base.scss",
    "app/assets/stylesheets/express_translate/buttons.scss",
    "app/assets/stylesheets/express_translate/express_translate.css.scss",
    "app/assets/stylesheets/express_translate/jquery-ui-1.10.4.css",
    "app/assets/stylesheets/express_translate/loading.css",
    "app/assets/stylesheets/express_translate/login.scss",
    "app/assets/stylesheets/express_translate/reset.css",
    "app/assets/stylesheets/express_translate/styles.scss",
    "app/assets/stylesheets/express_translate/wSelect.css",
    "app/controllers/express_translate/account_controller.rb",
    "app/controllers/express_translate/ajax/codes_controller.rb",
    "app/controllers/express_translate/ajax/languages_controller.rb",
    "app/controllers/express_translate/ajax/packages_controller.rb",
    "app/controllers/express_translate/base_controller.rb",
    "app/controllers/express_translate/files_controller.rb",
    "app/controllers/express_translate/options_controller.rb",
    "app/controllers/express_translate/services_controller.rb",
    "app/views/.DS_Store",
    "app/views/express_translate/.DS_Store",
    "app/views/express_translate/account/login.html.erb",
    "app/views/express_translate/ajax/languages/_content_language.html.erb",
    "app/views/express_translate/ajax/languages/language_update.html.erb",
    "app/views/express_translate/ajax/packages/_content_index.html.erb",
    "app/views/express_translate/ajax/packages/package_update.html.erb",
    "app/views/express_translate/options/.DS_Store",
    "app/views/express_translate/options/index.html.erb",
    "app/views/express_translate/options/language_detail.html.erb",
    "app/views/express_translate/options/languages.html.erb",
    "app/views/express_translate/templates/_code_item.html.erb",
    "app/views/layouts/express_translate/login.html.erb",
    "app/views/layouts/express_translate/translate.html.erb",
    "config/languages.yml",
    "config/routes.rb",
    "express_translate.gemspec",
    "lib/express_translate.rb",
    "lib/express_translate/account_management.rb",
    "lib/express_translate/database_management.rb",
    "lib/express_translate/express_translate_model.rb",
    "lib/express_translate/language_detail_management.rb",
    "lib/express_translate/languages_management.rb",
    "lib/express_translate/package_management.rb",
    "lib/generators/express_translate/install_generator.rb",
    "lib/generators/express_translate/reset_account_generator.rb",
    "lib/generators/express_translate/reset_generator.rb",
    "lib/generators/express_translate/seed_generator.rb",
    "lib/generators/express_translate/templates/config/express_translate.yml",
    "lib/seeds/accounts_seed.rb",
    "lib/seeds/languages_seed.rb",
    "lib/seeds/packages_seed.rb",
    "lib/tasks/watchr.rake",
    "node_modules/redis/.npmignore",
    "node_modules/redis/README.md",
    "node_modules/redis/benches/buffer_bench.js",
    "node_modules/redis/benches/hiredis_parser.js",
    "node_modules/redis/benches/re_sub_test.js",
    "node_modules/redis/benches/reconnect_test.js",
    "node_modules/redis/benches/stress/codec.js",
    "node_modules/redis/benches/stress/pubsub/pub.js",
    "node_modules/redis/benches/stress/pubsub/run",
    "node_modules/redis/benches/stress/pubsub/server.js",
    "node_modules/redis/benches/stress/rpushblpop/pub.js",
    "node_modules/redis/benches/stress/rpushblpop/run",
    "node_modules/redis/benches/stress/rpushblpop/server.js",
    "node_modules/redis/benches/stress/speed/00",
    "node_modules/redis/benches/stress/speed/plot",
    "node_modules/redis/benches/stress/speed/size-rate.png",
    "node_modules/redis/benches/stress/speed/speed.js",
    "node_modules/redis/benches/sub_quit_test.js",
    "node_modules/redis/changelog.md",
    "node_modules/redis/diff_multi_bench_output.js",
    "node_modules/redis/examples/auth.js",
    "node_modules/redis/examples/backpressure_drain.js",
    "node_modules/redis/examples/eval.js",
    "node_modules/redis/examples/extend.js",
    "node_modules/redis/examples/file.js",
    "node_modules/redis/examples/mget.js",
    "node_modules/redis/examples/monitor.js",
    "node_modules/redis/examples/multi.js",
    "node_modules/redis/examples/multi2.js",
    "node_modules/redis/examples/psubscribe.js",
    "node_modules/redis/examples/pub_sub.js",
    "node_modules/redis/examples/simple.js",
    "node_modules/redis/examples/sort.js",
    "node_modules/redis/examples/subqueries.js",
    "node_modules/redis/examples/subquery.js",
    "node_modules/redis/examples/unix_socket.js",
    "node_modules/redis/examples/web_server.js",
    "node_modules/redis/generate_commands.js",
    "node_modules/redis/index.js",
    "node_modules/redis/lib/commands.js",
    "node_modules/redis/lib/parser/hiredis.js",
    "node_modules/redis/lib/parser/javascript.js",
    "node_modules/redis/lib/queue.js",
    "node_modules/redis/lib/to_array.js",
    "node_modules/redis/lib/util.js",
    "node_modules/redis/multi_bench.js",
    "node_modules/redis/package.json",
    "node_modules/redis/test-unref.js",
    "node_modules/redis/test.js",
    "spec/.rspec",
    "spec/controllers/account_controller_spec.rb",
    "spec/controllers/ajax/codes_controller_spec.rb",
    "spec/controllers/ajax/languages_controller_spec.rb",
    "spec/controllers/ajax/packages_controller_spec.rb",
    "spec/controllers/files_controller_spec.rb",
    "spec/controllers/options_controller_spec.rb",
    "spec/controllers/services_controller_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_express_translate.rb"
  ]
  s.homepage = "https://github.com/RubifyTechnology/express_translate"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<hiredis>, [">= 0"])
      s.add_runtime_dependency(%q<actionpack>, [">= 3.2.0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<redis>, ["~> 3.1.0"])
      s.add_dependency(%q<hiredis>, [">= 0"])
      s.add_dependency(%q<actionpack>, [">= 3.2.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, ["~> 3.1.0"])
    s.add_dependency(%q<hiredis>, [">= 0"])
    s.add_dependency(%q<actionpack>, [">= 3.2.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

