# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rlang"
  s.version = "1.0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karl"]
  s.date = "2014-06-26"
  s.description = "longer description of your gem"
  s.email = "karl@rubify.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/.DS_Store",
    "app/assets/.DS_Store",
    "app/assets/images/.DS_Store",
    "app/assets/images/rubify_languages/.DS_Store",
    "app/assets/images/rubify_languages/add.png",
    "app/assets/images/rubify_languages/back.png",
    "app/assets/images/rubify_languages/blur.svg",
    "app/assets/images/rubify_languages/close.png",
    "app/assets/images/rubify_languages/embed.png",
    "app/assets/images/rubify_languages/file.png",
    "app/assets/images/rubify_languages/flags/Chad.png",
    "app/assets/images/rubify_languages/flags/ar.png",
    "app/assets/images/rubify_languages/flags/az.png",
    "app/assets/images/rubify_languages/flags/bg.png",
    "app/assets/images/rubify_languages/flags/bs.png",
    "app/assets/images/rubify_languages/flags/ca.png",
    "app/assets/images/rubify_languages/flags/cs.png",
    "app/assets/images/rubify_languages/flags/da.png",
    "app/assets/images/rubify_languages/flags/de.png",
    "app/assets/images/rubify_languages/flags/el.png",
    "app/assets/images/rubify_languages/flags/en-GB.png",
    "app/assets/images/rubify_languages/flags/en.png",
    "app/assets/images/rubify_languages/flags/es.png",
    "app/assets/images/rubify_languages/flags/et.png",
    "app/assets/images/rubify_languages/flags/fa.png",
    "app/assets/images/rubify_languages/flags/fi.png",
    "app/assets/images/rubify_languages/flags/fr.png",
    "app/assets/images/rubify_languages/flags/he.png",
    "app/assets/images/rubify_languages/flags/hr.png",
    "app/assets/images/rubify_languages/flags/hu.png",
    "app/assets/images/rubify_languages/flags/id.png",
    "app/assets/images/rubify_languages/flags/is.png",
    "app/assets/images/rubify_languages/flags/it.png",
    "app/assets/images/rubify_languages/flags/ja.png",
    "app/assets/images/rubify_languages/flags/ko.png",
    "app/assets/images/rubify_languages/flags/lt.png",
    "app/assets/images/rubify_languages/flags/lv.png",
    "app/assets/images/rubify_languages/flags/my.png",
    "app/assets/images/rubify_languages/flags/nb.png",
    "app/assets/images/rubify_languages/flags/nl.png",
    "app/assets/images/rubify_languages/flags/no.png",
    "app/assets/images/rubify_languages/flags/pl.png",
    "app/assets/images/rubify_languages/flags/pt-BR.png",
    "app/assets/images/rubify_languages/flags/pt.png",
    "app/assets/images/rubify_languages/flags/ro.png",
    "app/assets/images/rubify_languages/flags/ru.png",
    "app/assets/images/rubify_languages/flags/sk.png",
    "app/assets/images/rubify_languages/flags/sl.png",
    "app/assets/images/rubify_languages/flags/sv.png",
    "app/assets/images/rubify_languages/flags/th.png",
    "app/assets/images/rubify_languages/flags/tr.png",
    "app/assets/images/rubify_languages/flags/uk.png",
    "app/assets/images/rubify_languages/flags/vi.png",
    "app/assets/images/rubify_languages/flags/zh-CN.png",
    "app/assets/images/rubify_languages/flags/zh-HK.png",
    "app/assets/images/rubify_languages/flags/zh-TW.png",
    "app/assets/images/rubify_languages/jquery_ui/animated-overlay.gif",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_diagonals-thick_18_b81900_40x40.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_diagonals-thick_20_666666_40x40.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_flat_10_000000_40x100.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_glass_100_f6f6f6_1x400.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_glass_100_fdf5ce_1x400.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_glass_65_ffffff_1x400.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_gloss-wave_35_f6a828_500x100.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_highlight-soft_100_eeeeee_1x100.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-bg_highlight-soft_75_ffe45c_1x100.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-icons_222222_256x240.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-icons_228ef1_256x240.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-icons_ef8c08_256x240.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-icons_ffd27a_256x240.png",
    "app/assets/images/rubify_languages/jquery_ui/ui-icons_ffffff_256x240.png",
    "app/assets/images/rubify_languages/key-white.png",
    "app/assets/images/rubify_languages/login.png",
    "app/assets/images/rubify_languages/logout.png",
    "app/assets/images/rubify_languages/password.png",
    "app/assets/images/rubify_languages/remove.png",
    "app/assets/images/rubify_languages/setting.png",
    "app/assets/images/rubify_languages/username.png",
    "app/assets/images/rubify_languages/wselect/.DS_Store",
    "app/assets/images/rubify_languages/wselect/arrow-down.png",
    "app/assets/javascript/rubify_languages/application.js",
    "app/assets/javascript/rubify_languages/base.js",
    "app/assets/javascript/rubify_languages/bpopup.js",
    "app/assets/javascript/rubify_languages/jquery-ui-1.10.4.js",
    "app/assets/javascript/rubify_languages/login.js",
    "app/assets/javascript/rubify_languages/translate.layout.js",
    "app/assets/javascript/rubify_languages/wSelect.js",
    "app/assets/stylesheets/.DS_Store",
    "app/assets/stylesheets/rubify_languages/.DS_Store",
    "app/assets/stylesheets/rubify_languages/animate.css",
    "app/assets/stylesheets/rubify_languages/application.css",
    "app/assets/stylesheets/rubify_languages/base.scss",
    "app/assets/stylesheets/rubify_languages/buttons.scss",
    "app/assets/stylesheets/rubify_languages/jquery-ui-1.10.4.css",
    "app/assets/stylesheets/rubify_languages/loading.css",
    "app/assets/stylesheets/rubify_languages/login.scss",
    "app/assets/stylesheets/rubify_languages/reset.css",
    "app/assets/stylesheets/rubify_languages/rlang.css.scss",
    "app/assets/stylesheets/rubify_languages/styles.scss",
    "app/assets/stylesheets/rubify_languages/wSelect.css",
    "app/controllers/rubify_languages/account_controller.rb",
    "app/controllers/rubify_languages/base_controller.rb",
    "app/controllers/rubify_languages/options_controller.rb",
    "app/controllers/rubify_languages/services_controller.rb",
    "app/views/.DS_Store",
    "app/views/layouts/rubify_languages/login.html.erb",
    "app/views/layouts/rubify_languages/translate.html.erb",
    "app/views/rubify_languages/.DS_Store",
    "app/views/rubify_languages/account/login.html.erb",
    "app/views/rubify_languages/options/.DS_Store",
    "app/views/rubify_languages/options/_content_code.html.erb",
    "app/views/rubify_languages/options/_content_index.html.erb",
    "app/views/rubify_languages/options/_content_language.html.erb",
    "app/views/rubify_languages/options/_language.html.erb",
    "app/views/rubify_languages/options/code_update.html.erb",
    "app/views/rubify_languages/options/index.html.erb",
    "app/views/rubify_languages/options/language_detail.html.erb",
    "app/views/rubify_languages/options/language_update.html.erb",
    "app/views/rubify_languages/options/languages.html.erb",
    "app/views/rubify_languages/options/package_update.html.erb",
    "config/languages.yml",
    "config/rlang.yml",
    "config/routes.rb",
    "lib/generators/rubify_languages/install_generator.rb",
    "lib/rlang.rb",
    "lib/rubify_languages/account_management.rb",
    "lib/rubify_languages/database_management.rb",
    "lib/rubify_languages/language_detail_management.rb",
    "lib/rubify_languages/languages_management.rb",
    "lib/rubify_languages/package_management.rb",
    "lib/rubify_languages/rlang_model.rb",
    "lib/seeds/accounts_seed.rb",
    "lib/seeds/languages_seed.rb",
    "lib/seeds/packages_seed.rb",
    "node_modules/redis/.npmignore",
    "node_modules/redis/README.md",
    "node_modules/redis/benches/buffer_bench.js",
    "node_modules/redis/benches/hiredis_parser.js",
    "node_modules/redis/benches/re_sub_test.js",
    "node_modules/redis/benches/reconnect_test.js",
    "node_modules/redis/benches/stress/codec.js",
    "node_modules/redis/benches/stress/pubsub/pub.js",
    "node_modules/redis/benches/stress/pubsub/run",
    "node_modules/redis/benches/stress/pubsub/server.js",
    "node_modules/redis/benches/stress/rpushblpop/pub.js",
    "node_modules/redis/benches/stress/rpushblpop/run",
    "node_modules/redis/benches/stress/rpushblpop/server.js",
    "node_modules/redis/benches/stress/speed/00",
    "node_modules/redis/benches/stress/speed/plot",
    "node_modules/redis/benches/stress/speed/size-rate.png",
    "node_modules/redis/benches/stress/speed/speed.js",
    "node_modules/redis/benches/sub_quit_test.js",
    "node_modules/redis/changelog.md",
    "node_modules/redis/diff_multi_bench_output.js",
    "node_modules/redis/examples/auth.js",
    "node_modules/redis/examples/backpressure_drain.js",
    "node_modules/redis/examples/eval.js",
    "node_modules/redis/examples/extend.js",
    "node_modules/redis/examples/file.js",
    "node_modules/redis/examples/mget.js",
    "node_modules/redis/examples/monitor.js",
    "node_modules/redis/examples/multi.js",
    "node_modules/redis/examples/multi2.js",
    "node_modules/redis/examples/psubscribe.js",
    "node_modules/redis/examples/pub_sub.js",
    "node_modules/redis/examples/simple.js",
    "node_modules/redis/examples/sort.js",
    "node_modules/redis/examples/subqueries.js",
    "node_modules/redis/examples/subquery.js",
    "node_modules/redis/examples/unix_socket.js",
    "node_modules/redis/examples/web_server.js",
    "node_modules/redis/generate_commands.js",
    "node_modules/redis/index.js",
    "node_modules/redis/lib/commands.js",
    "node_modules/redis/lib/parser/hiredis.js",
    "node_modules/redis/lib/parser/javascript.js",
    "node_modules/redis/lib/queue.js",
    "node_modules/redis/lib/to_array.js",
    "node_modules/redis/lib/util.js",
    "node_modules/redis/multi_bench.js",
    "node_modules/redis/package.json",
    "node_modules/redis/test-unref.js",
    "node_modules/redis/test.js",
    "rlang.gemspec",
    "test/helper.rb",
    "test/test_rlang.rb"
  ]
  s.homepage = "https://github.com/KarlRubify/rlang"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<hiredis>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<redis>, ["~> 3.1.0"])
      s.add_dependency(%q<hiredis>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<redis>, ["~> 3.1.0"])
    s.add_dependency(%q<hiredis>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

