# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rlang"
  s.version = "1.0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karl"]
  s.date = "2014-06-10"
  s.description = "longer description of your gem"
  s.email = "karl@rubify.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/.DS_Store",
    "app/assets/.DS_Store",
    "app/assets/images/rubify_languages/background.png",
    "app/assets/images/rubify_languages/key.png",
    "app/assets/images/rubify_languages/back.png",
    "app/assets/images/rubify_languages/add.png",
    "app/assets/images/rubify_languages/loading.gif",
    "app/assets/javascript/rubify_languages/application.js",
    "app/assets/stylesheets/.DS_Store",
    "app/assets/stylesheets/rubify_languages/.DS_Store",
    "app/assets/stylesheets/rubify_languages/application.css",
    "app/assets/stylesheets/rubify_languages/reset.css",
    "app/assets/stylesheets/rubify_languages/styles.scss",
    "app/assets/stylesheets/rubify_languages/rlang.css.scss",
    "app/controllers/rubify_languages/options_controller.rb",
    "app/views/.DS_Store",
    "app/views/layouts/rubify_languages/translate.html.erb",
    "app/views/rubify_languages/.DS_Store",
    "app/views/rubify_languages/options/.DS_Store",
    "app/views/rubify_languages/options/_language.html.erb",
    "app/views/rubify_languages/options/index.html.erb",
    "config/routes.rb",
    "lib/rlang.rb",
    "rlang.gemspec",
    "test/helper.rb",
    "test/test_rlang.rb"
  ]
  s.homepage = "https://github.com/KarlRubify/rlang"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

