en: English
ar: Arabic
az: Azerbaijani
bg: Bulgarian
bs: Bosnian
ca: Catalan
cs: Czech
da: Danish
de: German
el: Greek
en-GB:  "English (United Kingdom)"
es: Spanish
et: Estonian
fa: Persian
fi: Finnish
fr: French
he: Hebrew
hr: Croatian
hu: Hungarian
id: Indonesian
is: Icelandic
it: Italian
ja: Japanese
ko: Korean
lt: Lithuanian
lv: Latvian
my:  Burmese
nb: "Norwegian Bokmål"
nl:  Dutch
no: Norwegian
pl:  Polish
pt:  Portuguese
pt-BR:  "Portuguese (Brazil)"
ro:  Romanian
ru:  Russian
sk:  Slovak
sl:  Slovenian
sv:  Swedish
th:  Thai
tr:  Turkish
uk:  Ukrainian
vi:  Vietnamese
zh-CN:  "Chinese (China)"
zh-HK:  "Chinese (Hong Kong)"
zh-TW:  "Chinese (Taiwan)"