connect:
  host: "0.0.0.0"
  port: 6379
  db: rubify_languages
  # password: "password"
  # path: "/tmp/redis.sock"
  
# Default
language:
  id: en
  text: English
package:
  id: be
  text: Backend
  
account: 
  - 
    username: "karl1"
    password: "password"
  - 
    username: "karl2"
    password: "password"

